#!/usr/bin/env python3
"""
03_build_fasta.py
=================
Builds patient-specific proteomics FASTA databases for use in
FragPipe / PEAKS / MSFragger.

For each patient, combines:
  1. Full UniProt reviewed human proteome (all ~20,000 proteins)
  2. Patient-specific variant peptides derived from VEP-annotated
     Mutect2 VCF files

The full reference is included (without expression filtering) to
ensure sufficient database size for PeptideProphet scoring.

Usage:
    python 03_build_fasta.py \
        --uniprot /path/to/uniprot_human_reviewed.fasta \
        --genemap /path/to/uniprot_genemap.tsv \
        --vcf_dir /path/to/vep_annotated \
        --outdir  /path/to/patient_fastas \
        --flank   10

Input:
    --uniprot   UniProt reviewed human proteome FASTA
                Download: see README
    --genemap   TSV mapping ENSEMBL gene IDs to UniProt accessions
                Generated by 02_generate_genemap.py
    --vcf_dir   Directory containing VEP-annotated VCF files
                Named <PATIENT>.vep.vcf (e.g. PDTO1.vep.vcf)
    --outdir    Output directory for patient-specific FASTAs
    --flank     Number of amino acids flanking the variant in
                the mutant peptide sequence (default: 10)

Output (per patient, in outdir):
    <PATIENT>_proteomics_db.fasta

VEP annotation requirements:
    VCF files must be annotated with VEP using at minimum:
    --symbol --canonical --protein --hgvs --hgvsp

Variant consequences included:
    missense_variant, stop_gained, stop_lost, start_lost,
    frameshift_variant, inframe_insertion, inframe_deletion,
    splice_region_variant

Requirements:
    pip install biopython pandas
"""

import argparse
import os
import re
from collections import defaultdict

import pandas as pd
from Bio import SeqIO
from Bio.Seq import Seq
from Bio.SeqRecord import SeqRecord

###############################################################################
# SETTINGS
# Update PATIENTS list to match your anonymized patient IDs
# VCF files must be named <PATIENT>.vep.vcf
###############################################################################
PATIENTS = ["PDTO1", "PDTO2", "PDTO3", "PDTO4", "PDTO5", "PDTO6"]  # CHANGE THIS: list your patient IDs

INCLUDED_CONSEQUENCES = {
    "missense_variant",
    "stop_gained",
    "stop_lost",
    "start_lost",
    "frameshift_variant",
    "inframe_insertion",
    "inframe_deletion",
    "splice_region_variant",
}

###############################################################################
# ARGUMENT PARSING
###############################################################################
def parse_args():
    parser = argparse.ArgumentParser(
        description="Build patient-specific proteomics FASTAs for FragPipe/PEAKS."
    )
    parser.add_argument("--uniprot", required=True,
                        help="UniProt reviewed human proteome FASTA")
    parser.add_argument("--genemap", required=True,
                        help="TSV mapping ENSEMBL gene IDs to UniProt accessions")
    parser.add_argument("--vcf_dir", required=True,
                        help="Directory with VEP-annotated VCFs (<PATIENT>.vep.vcf)")
    parser.add_argument("--outdir",  required=True,
                        help="Output directory for patient FASTAs")
    parser.add_argument("--flank",   type=int, default=10,
                        help="AA flanking variant in mutant peptide (default: 10)")
    return parser.parse_args()

###############################################################################
# STEP 1: LOAD UNIPROT FASTA
###############################################################################
def load_uniprot(fasta_path):
    """Load UniProt FASTA into dict: accession -> SeqRecord."""
    print(f"Loading UniProt FASTA: {fasta_path}")
    records = {}
    for rec in SeqIO.parse(fasta_path, "fasta"):
        # UniProt header: sp|ACCESSION|ENTRY_NAME Description
        parts = rec.id.split("|")
        accession = parts[1] if len(parts) >= 2 else rec.id
        records[accession] = rec
    print(f"  -> {len(records)} proteins loaded")
    return records

###############################################################################
# STEP 2: LOAD GENE -> UNIPROT MAPPING
###############################################################################
def load_genemap(genemap_path):
    """Load ENSEMBL gene ID -> UniProt accession mapping."""
    print(f"Loading gene map: {genemap_path}")
    df = pd.read_csv(genemap_path, sep="\t")
    gene_name_to_uniprot = defaultdict(set)
    for _, row in df.iterrows():
        acc  = str(row.get("uniprot_accession", "")).strip()
        gene = str(row.get("gene_name", "")).strip()
        if gene and acc and gene != "nan" and acc != "nan":
            gene_name_to_uniprot[gene].add(acc)
    print(f"  -> {len(gene_name_to_uniprot)} gene names mapped")
    return gene_name_to_uniprot

###############################################################################
# STEP 3: PARSE VEP-ANNOTATED VCF
###############################################################################
def parse_vep_vcf(vcf_path):
    """
    Parse a VEP-annotated VCF file.
    Returns list of dicts for PASS variants on canonical transcripts
    with relevant consequences.
    """
    variants = []
    csq_fields = []

    # Extract CSQ field order from VEP header
    with open(vcf_path) as f:
        for line in f:
            if line.startswith("##INFO=<ID=CSQ"):
                match = re.search(r'Format: ([^"]+)"', line)
                if match:
                    csq_fields = match.group(1).strip().split("|")
                break

    if not csq_fields:
        print(f"  WARNING: No CSQ format found in {vcf_path}. Is this VEP-annotated?")
        return variants

    # Parse variants
    with open(vcf_path) as f:
        for line in f:
            if line.startswith("#"):
                continue
            fields = line.strip().split("\t")
            if len(fields) < 8:
                continue

            chrom, pos, vid, ref, alt, qual, filt, info = fields[:8]

            # Only keep PASS variants
            if filt != "PASS":
                continue

            csq_match = re.search(r'CSQ=([^;]+)', info)
            if not csq_match:
                continue

            for entry in csq_match.group(1).split(","):
                vals = entry.split("|")
                csq = dict(zip(csq_fields, vals))

                # Filter by consequence type
                conseq_list = csq.get("Consequence", "").split("&")
                if not any(c in INCLUDED_CONSEQUENCES for c in conseq_list):
                    continue

                # Only use canonical transcript
                if csq.get("CANONICAL", "") != "YES":
                    continue

                variants.append({
                    "consequence": csq.get("Consequence", ""),
                    "gene":        csq.get("SYMBOL", ""),
                    "hgvsp":       csq.get("HGVSp", ""),
                    "amino_acids": csq.get("Amino_acids", ""),
                    "protein_pos": csq.get("Protein_position", ""),
                    "uniprot":     csq.get("SWISSPROT", ""),
                })

    print(f"  -> {len(variants)} PASS variants with relevant consequences")
    return variants

###############################################################################
# STEP 4: GENERATE MUTANT PEPTIDE SEQUENCES
###############################################################################
def generate_mutant_peptide(ref_seq, protein_pos, amino_acids, flank):
    """
    Generate a mutant peptide sequence around a variant.

    ref_seq:     Full reference protein sequence (string)
    protein_pos: VEP protein position (e.g. "123" or "123-125")
    amino_acids: VEP amino_acids field (e.g. "A/V" for missense)
    flank:       Number of AAs to include on each side of the variant

    Returns mutant peptide string, or None if generation fails.
    Minimum peptide length is 7 AA (required for MS identification).
    """
    try:
        pos = int(protein_pos.split("-")[0]) - 1  # Convert to 0-based
        if "/" not in amino_acids:
            return None

        ref_aa, alt_aa = amino_acids.split("/")[:2]
        if alt_aa == "-":
            alt_aa = ""

        seq_list = list(str(ref_seq))
        ref_len = len(ref_aa) if ref_aa != "-" else 0
        seq_list[pos:pos + ref_len] = list(alt_aa)
        mutant_seq = "".join(seq_list)

        start = max(0, pos - flank)
        end = min(len(mutant_seq), pos + len(alt_aa) + flank)
        peptide = mutant_seq[start:end]

        if "*" in peptide:
            peptide = peptide.split("*")[0]

        return peptide if len(peptide) >= 7 else None

    except Exception:
        return None

###############################################################################
# MAIN
###############################################################################
def main():
    args = parse_args()
    os.makedirs(args.outdir, exist_ok=True)

    # Load shared resources
    uniprot_records      = load_uniprot(args.uniprot)
    gene_name_to_uniprot = load_genemap(args.genemap)

    # Full reference as list (same for every patient)
    ref_records = list(uniprot_records.values())
    print(f"\nFull reference: {len(ref_records)} proteins (used for all patients)")

    summary_rows = []

    for patient in PATIENTS:
        print(f"\n{'='*60}")
        print(f"Processing patient: {patient}")
        print(f"{'='*60}")

        # Load VEP-annotated VCF
        vcf_path = os.path.join(args.vcf_dir, f"{patient}.vep.vcf")
        if not os.path.exists(vcf_path):
            print(f"  WARNING: VCF not found: {vcf_path}, skipping variant step.")
            variants = []
        else:
            variants = parse_vep_vcf(vcf_path)

        # Generate variant peptide records
        variant_records = []
        skipped = 0

        for var in variants:
            # Try direct UniProt accession from VEP annotation first
            uniprot_acc = var.get("uniprot", "").split("&")[0].strip()

            # Fall back to gene name lookup
            if not uniprot_acc or uniprot_acc not in uniprot_records:
                accs = gene_name_to_uniprot.get(var["gene"], set())
                uniprot_acc = next(iter(accs), None)

            if not uniprot_acc or uniprot_acc not in uniprot_records:
                skipped += 1
                continue

            ref_seq   = str(uniprot_records[uniprot_acc].seq)
            aa_change = var["amino_acids"]
            prot_pos  = var["protein_pos"]

            if not aa_change or not prot_pos or "/" not in aa_change:
                skipped += 1
                continue

            peptide = generate_mutant_peptide(ref_seq, prot_pos, aa_change, args.flank)
            if not peptide:
                skipped += 1
                continue

            var_id = (
                f"VAR_{patient}_{var['gene']}_"
                f"{var['hgvsp'].replace(':', '_').replace('>', '_')}"
            )
            variant_records.append(SeqRecord(
                seq=Seq(peptide),
                id=var_id,
                description=(
                    f"patient={patient} gene={var['gene']} "
                    f"consequence={var['consequence']} "
                    f"hgvsp={var['hgvsp']} [VARIANT_PEPTIDE]"
                ),
            ))

        print(f"  -> {len(variant_records)} variant peptides added ({skipped} skipped)")

        # Write: full reference + variant peptides
        out_fasta = os.path.join(args.outdir, f"{patient}_proteomics_db.fasta")
        SeqIO.write(ref_records + variant_records, out_fasta, "fasta")
        print(f"  Written: {out_fasta} "
              f"({len(ref_records) + len(variant_records)} total entries)")

        summary_rows.append({
            "patient":            patient,
            "reference_proteins": len(ref_records),
            "variant_peptides":   len(variant_records),
            "total_entries":      len(ref_records) + len(variant_records),
        })

    # Print final summary
    print(f"\n{'='*60}")
    print("FINAL SUMMARY")
    print("="*60)
    df = pd.DataFrame(summary_rows)
    print(df.to_string(index=False))
    print(f"\nAll FASTAs saved to: {args.outdir}")
    print("Done!")

if __name__ == "__main__":
    main()
